Implements User
lucmkz/sdk-nodejs pull request #13
Opened 2023-09-13 14:05 UTC by taliyada

## 📝 Description

Implements User Client to get information about the user

### ✅ Checklist:

- [x] I followed the instructions indicated in [Contribution Guidelines](CONTRIBUTING.md)
- [x] Added the necessary tests for the code or functionality that I'm working on
- [x] I ran the tests and made sure they work
- [x] My branch coverage is at least 80%
- [x] I verified the style of my code matches the one in the project

## 🧰 How to reproduce

- Step by step of how to test, specially for bugs.
- Links of external docs.

## 📄 References

- Links do external documentation
- Diagrams
- Useful links

2023-09-13 14:53 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +export declare type UserResponse = {
Tali olhando o php faltam muitas propriedades, veja:
https://github.com/mercadopago/sdk-php/blob/develop-v3/src/MercadoPago/Resources/User.php

2023-09-13 16:48 UTC, taliyada commented on src/clients/user/get/types.ts
> +export declare type UserResponse = {
@eltinMeli na SDK de Java tem mapeados menos campos, qual dos dois a gente segue?
https://github.com/mercadopago/sdk-java/blob/master/src/main/java/com/mercadopago/resources/user/User.java

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +  countryId: string;
```suggestion
  country_id: string;
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +  alternativePhone: {
```suggestion
  alternative_phone: {
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +  sellerExperience?: string;
```suggestion
  seller_experience?: string;
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +    acceptCreditNote?: string;
```suggestion
    accept_credit_note?: string;
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +  sellerReputation: {
```suggestion
  seller_reputation: {
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +  userType?: string;
```suggestion
  user_type?: string;
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +    areaCode: string;
```suggestion
    area_code: string;
```

2023-09-13 21:01 UTC, eltinMeli commented on src/clients/user/get/types.ts
> +    areaCode: string;
```suggestion
    area_code: string;
```

2023-09-14 17:31 UTC, eltinMeli approved these changes

2023-09-15 14:06 UTC, lucmkz requested changes

2023-09-15 14:06 UTC, lucmkz commented on src/clients/user/get/types.ts
> +  seller_reputation: {
não vamos deixar acontecer essa identação aqui, vamos sempre criar as tipagens para cada atributo, pois elas podem ser reutilizadas em algum momento, isso vale para as outras ocorrencias tb

2023-09-18 15:55 UTC, lucmkz requested changes

2023-09-18 15:55 UTC, lucmkz commented on src/clients/user/get/types.ts
> +    canceled: number;
remover todas as indentações
sempre declarar o tipo de cada atributo, o meso vale para as outras ocorrências

2023-09-18 18:30 UTC, lucmkz approved these changes

2023-09-18 18:33 UTC, merged