Feature/corech2 1293 add card
lucmkz/sdk-nodejs pull request #2
Opened 2023-08-25 17:22 UTC by edmarSoaress

## Cambios realizados para el feature:
 *  Add card Implementation

2023-08-25 18:54 UTC, lucmkz requested changes

2023-08-25 18:54 UTC, lucmkz commented on .nvmrc
>  v16
aqui teria que ficar apenas o v16
deu problema no merge aqui

2023-08-25 18:54 UTC, lucmkz commented on .gitignore
> +package-lock.json
o package-lock não pode ficar no gitignore, deve ser enviado ao repositório junto do restante dos arquivos 

https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

2023-08-25 18:54 UTC, lucmkz commented on src/clients/customer/commonTypes.ts
> +export declare class CustomerCardPaymentMethod {
porque declare `class`? 
O ideal aqui é manter o declare `type`, foi assim por algum motivo específico?

2023-08-25 18:54 UTC, lucmkz commented on src/clients/customer/commonTypes.ts
> +	readonly id: string;
por que o readonly? 
é necessário? 
Se não, remove isso por favor...

2023-08-25 18:54 UTC, lucmkz commented on src/clients/customer/commonTypes.ts
> +import { Identification } from '../commonTypes';
faltou o type no `import` qui e percebi que também faltou em outros lugares, se puder dar uma checada geral...

2023-08-25 18:54 UTC, lucmkz commented on src/clients/customer/get/types.ts
> +
apaga essas linhas extras também
deixa apenas uma

2023-08-25 18:59 UTC, edmarSoaress commented on src/clients/customer/commonTypes.ts
> +export declare class CustomerCardPaymentMethod {
Erro de javeiro!

2023-08-25 19:36 UTC, edmarSoaress commented on src/clients/customer/commonTypes.ts
> +	readonly id: string;
Creio que não se faz necessário, fiz baseado na sdk de java em que os campos estavam como final

2023-08-28 13:14 UTC, lucmkz requested changes

2023-08-28 13:14 UTC, lucmkz commented on src/clients/customer/get/types.ts
> +import { MercadoPagoConfig } from '@src/mercadoPagoConfig';
faltou `type` aqui

2023-08-28 13:14 UTC, lucmkz commented on src/clients/customer/list/types.ts
> +import { MercadoPagoConfig } from '@src/mercadoPagoConfig';
`type` aqui

2023-08-28 13:28 UTC, lucmkz approved these changes

2023-08-28 13:28 UTC, merged