implements invoices module
lucmkz/sdk-nodejs pull request #24
Opened 2023-09-21 14:08 UTC by taliyada

## 📝 Description

Implements Invoices modules
Ref. https://www.mercadopago.com.br/developers/pt/reference/subscriptions/_authorized_payments_id/get

### ✅ Checklist:

- [x] I followed the instructions indicated in [Contribution Guidelines](CONTRIBUTING.md)
- [x] Added the necessary tests for the code or functionality that I'm working on
- [x] I ran the tests and made sure they work
- [x] My branch coverage is at least 80%
- [x] I verified the style of my code matches the one in the project

## 🧰 How to reproduce

- Step by step of how to test, specially for bugs.
- Links of external docs.

## 📸 Screenshots

- Before and after, if it's a fix for a bug.

## 📄 References

- Links do external documentation
- Diagrams
- Useful links

2023-09-21 14:13 UTC, lucmkz approved these changes

2023-09-21 17:53 UTC, rhames07 approved these changes

2023-09-22 13:34 UTC, lucmkz requested changes

2023-09-22 13:34 UTC, lucmkz commented on src/examples/src/invoices/search.ts
> +	preapproval_id: 'test',
```suggestion
	preapproval_id: '<PREAPPROVAL_ID>',
```

2023-09-22 14:08 UTC, lucmkz approved these changes

2023-09-22 14:11 UTC, merged