Implementação Preference
lucmkz/sdk-nodejs pull request #3
Opened 2023-08-25 22:12 UTC by brunacamposxx

## Cambios realizados para el feature:
 * Implementação Preference
\
## Checklist validación PR:

- [ ] Título y descripción clara del PR
- [ ] Tests de mi funcionalidad 
- [ ] Documentación de mi funcionalidad
- [ ] Tests ejecutados y pasados
- [ ] Branch Coverage >= 80%

2023-08-28 13:17 UTC, lucmkz requested changes

2023-08-28 13:17 UTC, lucmkz commented on src/clients/preferences/commonTypes.ts
> +import { Identification } from '@src/clients/commonTypes';
import `type` aqui

2023-08-28 13:17 UTC, lucmkz commented on src/clients/preferences/create/create.spec.ts
> +import { MercadoPagoConfig } from '@src/mercadoPagoConfig';
tomas as importações de tipagem, precisa adicionar o `type`

2023-08-28 18:41 UTC, eltinMeli commented on src/clients/preferences/commonTypes.ts
> +  default_card_id?: string;
Não encontrei essa propriedade tanto na doc quando no sdk-java

2023-08-28 18:41 UTC, eltinMeli commented on src/clients/preferences/index.ts
> + */
A identação ficou estranha

2023-08-28 18:41 UTC, eltinMeli commented on src/examples/src/preferences/create/create.ts
> +	],
Não poderiamos colocar mais campos?

``` json
{    
    "external_reference": "teste_eltin",
    "items": [
        {
            "id": "4567",
            "title": "Videogame",
            "description": "Playstation",
            "picture_url": "http://i.mlcdn.com.br/portaldalu/fotosconteudo/48029_01.jpg",
            "category_id": "eletronico",
            "quantity": 2,
            "currency_id": "BRL",
            "unit_price": 5.00
        }
    ],
    "payment_methods": {
        "default_payment_method_id": "master",
        "excluded_payment_types": [
            {
                "id": "ticket"
            }
        ],
        "excluded_payment_methods": [
            {
                "id": ""
            }
        ],
        "installments": 12,
        "default_installments": 1
    }
}
```

2023-08-28 18:41 UTC, eltinMeli commented on src/examples/src/preferences/get/get.ts
> +
Não precisa dessa separação em duas linhas

2023-08-28 18:41 UTC, eltinMeli commented on src/examples/src/preferences/search/search.ts
> +
Não precisa dessa separação

2023-08-28 18:41 UTC, eltinMeli commented on src/examples/src/preferences/update/update.ts
> +
Não precisa dessa separação

2023-08-28 19:25 UTC, brunacamposxx commented on src/clients/preferences/commonTypes.ts
> +  default_card_id?: string;
O campo é retornado quando chamo a api de preference. Removo?
<img width="363" alt="Captura de Tela 2023-08-28 às 16 25 26" src="https://github.com/lucmkz/sdk-nodejs/assets/68570989/38438eba-61c7-4906-9272-a3f8e9facc9c">

2023-08-28 21:20 UTC, eltinMeli approved these changes

2023-08-28 21:20 UTC, eltinMeli commented on src/clients/preferences/commonTypes.ts
> +  default_card_id?: string;
Não precisa, se volta mantém

2023-08-29 14:02 UTC, edmarSoaress approved these changes

2023-08-29 17:04 UTC, lucmkz approved these changes

2023-08-29 17:04 UTC, merged