Refund
lucmkz/sdk-nodejs pull request #4
Opened 2023-08-29 15:09 UTC by brunacamposxx

## Cambios realizados para el feature:
- Refund 
 

## Checklist validación PR:

- [ ] Título y descripción clara del PR
- [ ] Tests de mi funcionalidad 
- [ ] Documentación de mi funcionalidad
- [ ] Tests ejecutados y pasados
- [ ] Branch Coverage >= 80%

2023-08-31 12:15 UTC, lucmantovani commented on src/clients/paymentsRefunds/commonTypes.ts
> +  metadata: Array<string>; // conferir -> devsite = array -> postman -> objeto
Acredito que deveríamos seguir o Postman, porque é o que realmente recebemos
E nos casos em que estiver diferente do Devsite, solicitar a alteração

2023-08-31 12:16 UTC, lucmantovani commented on src/clients/paymentsRefunds/commonTypes.ts
> +  expiration_date: string; // conferir
Se não me engano existe o tipo `Date`
Podemos ver como fica se usarmos ele

2023-08-31 12:53 UTC, eltinMeli commented on src/clients/paymentsRefunds/commonTypes.ts
> +  source: Array<Source>;
Source é um objeto, no dev site está errado.

2023-08-31 12:53 UTC, eltinMeli commented on src/clients/paymentsRefunds/commonTypes.ts
> +  metadata: Array<string>; // conferir -> devsite = array -> postman -> objeto
Isso mesmo, olha no retorno da api que está
``` json
  "metadata": {
    "status_detail": null
  },
```

2023-08-31 12:53 UTC, eltinMeli commented on src/clients/paymentsRefunds/get/types.ts
> +export declare type GetRefundByRefundId = {
por estar dentro de paymentsRefunds não poderia ser apenas Get?
```suggestion
export declare type Get = {
```

2023-08-31 12:53 UTC, eltinMeli commented on src/clients/paymentsRefunds/index.ts
> +		return get({ payment_id, refund_id: refund_id, config: this.config });
Como está com msm nome, precisa repetir?
```suggestion
		return get({ payment_id, refund_id, config: this.config });
```

2023-08-31 14:42 UTC, brunacamposxx commented on src/clients/paymentsRefunds/commonTypes.ts
> +  metadata: Array<string>; // conferir -> devsite = array -> postman -> objeto
Perguntei ao Lucão qual a melhor tipagem para esse campo 'metadata', chegou-se a conclusão de usar 'any'. Lucão corrigiu também nos outros clients que o utilizam.

2023-08-31 14:44 UTC, brunacamposxx commented on src/clients/paymentsRefunds/commonTypes.ts
> +  expiration_date: string; // conferir
Como expiration_date e additional_data retornam null e não estão sendo mapeados nas outras sdks, Lucão achou melhor remover esses campos daqui também.

2023-08-31 14:44 UTC, brunacamposxx commented on src/clients/paymentsRefunds/commonTypes.ts
> +  source: Array<Source>;
Corrigido!

2023-08-31 14:44 UTC, brunacamposxx commented on src/clients/paymentsRefunds/get/types.ts
> +export declare type GetRefundByRefundId = {
Perfeito! Corrigido!

2023-08-31 14:45 UTC, brunacamposxx commented on src/clients/paymentsRefunds/index.ts
> +		return get({ payment_id, refund_id: refund_id, config: this.config });
Corrigido!

2023-08-31 16:25 UTC, eltinMeli approved these changes

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/commonTypes.ts
> +  metadata: any;
```suggestion
  metadata: object[];
```

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/commonTypes.ts
> +  amount_refunded_to_payer: number;
Na referência de api não existe `amount_refunded_to_payer`, mas existe `partition_details` e `label`. Acho que vale verificar esses campos

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/create/create.spec.ts
> +	test('should successfully make a request with the body "amount"', async () => {
```suggestion
	test('should successfully make a request with "amount" in the body', async () => {
```

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/get/get.spec.ts
> +	test('should find a refund by refund_id ', async () => {
```suggestion
	test('should include the refund_id in the path of the url ', async () => {
```
essa sugestão é porque a descrição que tinha antes não condiz com o que o teste verifica. Ser capaz de encontrar um refund por id faria mais sentido num teste de integração.

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/getList/getList.spec.ts
> +import getList from '.';
Para manter padrão com os outros clients, seria melhor chamar essa operação simplesmente de `list`.

Para renomear, sugiro usar o comando `git mv <caminho para arquivo atual> <caminho para o arquivo com o nome novo>`

2023-08-31 20:32 UTC, romerosilva-meli commented on src/clients/paymentsRefunds/getList/getList.spec.ts
> +	test('should find a refund by payment_id ', async () => {
Mesma sugestão de um teste anterior, usar uma descrição que passe melhor a idéia do que o teste faz

2023-09-04 18:42 UTC, brunacamposxx commented on src/clients/paymentsRefunds/commonTypes.ts
> +  amount_refunded_to_payer: number;
Acredito que o devsite esteja desatualizado. amount_refunded_to_payer retorna quando chamamos a api.

partition_details e labels não foram mapeados nas sdks de java e php, ao menos eu não encontrei, e retornam um array vazio. acha que vale adicionar aqui?

2023-09-04 18:43 UTC, brunacamposxx commented on src/clients/paymentsRefunds/get/get.spec.ts
> +	test('should find a refund by refund_id ', async () => {
Perfeito! Obrigada, Romero :)

2023-09-05 13:32 UTC, lucmkz requested changes

2023-09-05 13:32 UTC, lucmkz commented on src/clients/paymentsRefunds/commonTypes.ts
> +  metadata: Array<string>; // conferir -> devsite = array -> postman -> objeto
concordo, vamos seguir sempre o retorno da API, e anotar as inconsistência, depois reportar

já que no devsite não diz o que pode ser esse metadata, vamos tipar como `any` mesmo

2023-09-05 13:32 UTC, lucmkz commented on src/examples/src/paymentsRefunds/create/create.ts
> + * @see {@link https://www.mercadopago.com.br/developers/pt/reference/chargebacks/_payments_id_refunds/post Documentation }.
bruna, vamos colocar a documentação sempre em inglês, é só mudar de `pt` para `en`
```suggestion
 * @see {@link https://www.mercadopago.com.br/developers/en/reference/chargebacks/_payments_id_refunds/post Documentation }.
```

da uma checada nos outros exemplos, existem mais casos

2023-09-05 13:36 UTC, lucmantovani commented on src/examples/src/paymentsRefunds/create/create.ts
> + * @see {@link https://www.mercadopago.com.br/developers/pt/reference/chargebacks/_payments_id_refunds/post Documentation }.
Acrescentando a esse ponto, acredito que deveríamos deixar somente `https://www.mercadopago.com`

2023-09-05 14:59 UTC, brunacamposxx commented on src/examples/src/paymentsRefunds/create/create.ts
> + * @see {@link https://www.mercadopago.com.br/developers/pt/reference/chargebacks/_payments_id_refunds/post Documentation }.
Feito!

2023-09-06 12:22 UTC, lucmkz approved these changes

2023-09-06 12:22 UTC, merged